version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - /home/sann_htet/Desktop/PythonAPIDevelopment:/home/sann_htet/Desktop/PythonAPIDevelopment:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - /home/sann_htet/Desktop/PythonAPIDevelopment/.env
    
  postgres:
    image: postgres
    env_file:
      - /home/sann_htet/Desktop/PythonAPIDevelopment/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db:
